name: KiBot_GitHub_Actions  # Can by any name
on: 
  pull_request:
    paths:
    - 'jlink-adapter-PCB/**'
jobs:
  KiBot-Generation:  # Can be any name
    runs-on: ubuntu-latest  # Don't change
    container: ghcr.io/inti-cmnb/kicad7_auto:latest  # Don't Change

    steps:  
    - name: Checkout repo
      uses: actions/checkout@v3  # Github built-in repo checkout step.

    # Start of the KiBot steps
    - name: Run KiBot
      run: |
        cd jlink-adapter-PCB
        kibot -e "jlink-adapter.kicad_sch" -c "config.kibot.yaml"

    - name: Retrieve results
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: Fabrication_Main
        path: |
          pcb_main/Fabrication/
        if-no-files-found: warn