name: KiBot_GitHub_Actions # Can by any name
on:
  pull_request:
    paths:
      - "SAO_tree_ornament/**"
jobs:
  KiBot-Generation: # Can be any name
    runs-on: ubuntu-latest # Don't change
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 # Github built-in repo checkout step.
        with:
          submodules: recursive
          token: ${{ secrets.CI_SKEC_KICAD_LIBS_SECRET }}
      - name: Run KiBot
        uses: INTI-CMNB/KiBot@v2_k9
        with:
          config: SAO_tree_ornament/config.kibot.yaml
          dir: SAO_tree_ornament
          schema: "SAO_tree_ornament/SAO_tree_ornament.kicad_sch"
          board: "SAO_tree_ornament/SAO_tree_ornament.kicad_pcb"
      - name: Retrieve results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Fabrication_Main
          path: |
            pcb_main/Fabrication/
          if-no-files-found: warn
